### ISSUE TITLE
TARGET - PROPERTY 작업 실패 [job 1808]

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#3]
TARGEt - PROPERTY 를 수행했는데, 실패했습니다.

job 1808을 실행했는데, 실패했습니다. 원인을 알고 싶습니다.

**Comment by arontier-dmjeong** [comment]
@jsko-arontier 

문의 주신 job의 전체 erro log 파일과 최초 Error 발생 지점 로그입니다.

[job_1808_stderr.tar.gz](https://github.com/arontier/ad3/files/7850638/job_1808_stderr.tar.gz)

기존 example로 실행시켰을 때 정상 동작되는 것을 확인하였고 
오류가 난 job의 input으로 직접 테스트한 경우에 동일한 error가 발생하였습니다. 

```
---
Starting Secondary Structure (p20k_secondary_structure) on Tue Jan 11 14:25:46 KST 2022
---
Matplotlib created a temporary config/cache directory at /cromwell-executions/X0000002109/eaa1ba91-0cb4-4775-b435-523b770dd6f8/call-Predict/tmp.89ddff7b/matplotlib-68bwn3kt because

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/managers.py", line 1674, in create_block_manager_from_blocks
    mgr = BlockManager(blocks, axes)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core
/internals/managers.py", line 149, in __init__
    self._verify_integrity()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/managers.py", line 329, in _verify_integrity
    raise construction_error(tot_items, block.shape[1:], self.axes)
ValueError: Shape of passed values is (959, 8), indices imply (1114, 8)
